
[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = 'call echodoc#enable()'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <silent>L     <Plug>(neosnippet_jump_or_expand)
  smap <silent>L     <Plug>(neosnippet_jump_or_expand)
  xmap <silent>L     <Plug>(neosnippet_expand_target)
  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_complete_done = 1
  let g:neosnippet#expand_word_boundary = 1

  let g:neosnippet#snippets_directory = '~/.vim/snippets'
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['neocomplete.vim', 'deoplete.nvim']

# [[plugins]]
# repo = 'Shougo/vinarise.vim'
# on_cmd = 'Vinarise'
# hook_add = 'let g:vinarise_enable_auto_detect = 1'

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'LeafCage/foldCC'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-scouter'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

# [[plugins]]
# repo = 'yonchu/accelerated-smooth-scroll'
# on_path = '.*'
# hook_add = '''
#   let g:ac_smooth_scroll_enable_accelerating = 0
# '''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = 'xmap p <Plug>(operator-replace)'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>ys <Plug>(operator-surround-append)a
  nmap <silent>ds <Plug>(operator-surround-delete)a
  nmap <silent>cs <Plug>(operator-surround-replace)a
'''

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
on_map = {ox = '<Plug>'}

[[plugins]]
repo = 'saihoooooooo/glowshi-ft.vim'
on_map = '<Plug>'
hook_add = '''
  let g:glowshi_ft_no_default_key_mappings = 1
  map f <Plug>(glowshi-ft-f)
  map F <Plug>(glowshi-ft-F)

  let g:glowshi_ft_timeoutlen = 1000
'''

[[plugins]]
repo = 'lambdalisue/vim-findent'
on_if = 1
hook_add = '''
  " Note: It is too slow.
  autocmd MyAutoCmd BufRead * Findent! --no-warnings
  " nnoremap <silent> [Space]i    :<C-u>Findent! --no-warnings<CR>
'''

[[plugins]]
repo = 'Konfekt/FastFold'
on_path = '.*'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap s <Plug>(easymotion-s2)
  xmap s <Plug>(easymotion-s2)
  omap z <Plug>(easymotion-s2)
  nmap g/ <Plug>(easymotion-sn)
  xmap g/ <Plug>(easymotion-sn)
  omap g/ <Plug>(easymotion-tn)
  let g:EasyMotion_smartcase = 1
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)
  let g:EasyMotion_startofline = 0
  let g:EasyMotion_keys = 'QZASDFGHJKL'
  let g:EasyMotion_use_upper = 1
  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1
  let g:EasyMotion_use_migemo = 0

  hi link EasyMotionTarget Special
  hi link EasyMotionShade  Comment
  hi link EasyMotionTarget2First Type
  hi link EasyMotionTarget2Second Type
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:precious_enable_switch_CursorMoved = { '*': 0 }
  autocmd MyAutoCmd InsertEnter * PreciousSwitch
  autocmd MyAutoCmd InsertLeave * PreciousReset
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
on_map = '<Plug>'

[[plugins]]
repo = 'kana/vim-smartword'
on_map = '<Plug>'
hook_add = '''
  map w <Plug>(smartword-w)
  map b <Plug>(smartword-b)
  map e <Plug>(smartword-e)
  map ge <Plug>(smartword-ge)
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'
hook_add = '''
  let g:gitgutter_realtime = 0
  let g:gitgutter_eager = 0
  nnoremap <Leader>gg :<C-u>GitGutterToggle<CR>
  nnoremap <Leader>gh :<C-u>GitGutterLineHighlightsToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_path = '.*'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript']
hook_source = '''
    let g:user_emmet_mode = 'i'
    let g:user_emmet_leader_key='<C-E>'
    let g:use_emmet_complete_tag = 1
    let g:user_emmet_settings = {
    \   'variables': {
    \       'lang': "ja"
    \   },
    \   'indentation': '    '
    \}
'''

[[plugins]]
repo = 'kewah/vim-stylefmt'
on_ft = ['css', 'less', 'scss', 'sass']
hook_add = '''
nnoremap <silent> <leader>cs :Stylefmt<CR>
vnoremap <silent> <leader>cs :StylefmtVisual<CR>
'''

[[plugins]]
repo = 'csscomb/vim-csscomb'
on_ft = ['css', 'less', 'scss', 'sass']
hook_add = '''
" Map bc to run CSScomb. bc stands for beautify css
autocmd FileType css noremap <buffer> <leader>bc :CSScomb<CR>
'''

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
on_ft = ['html', 'css', 'javascript']
hook_source = '''
autocmd FileType javascript vnoremap <buffer>  <c-f> :call RangeJsBeautify()<cr>
autocmd FileType json vnoremap <buffer> <c-f> :call RangeJsonBeautify()<cr>
autocmd FileType jsx vnoremap <buffer> <c-f> :call RangeJsxBeautify()<cr>
autocmd FileType html vnoremap <buffer> <c-f> :call RangeHtmlBeautify()<cr>
autocmd FileType css vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>
'''

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['html', 'css', 'less', 'scss', 'sass']

[[plugins]]
repo = 'tyru/caw.vim'
on_path = '.*'
hook_add = '''
  nmap <Leader>/ <Plug>(caw:hatpos:toggle)
  vmap <Leader>/ <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'itspriddle/vim-marked'
on_ft = 'markdown'
hook_add = '''
  if has('mac')
    let g:marked_app = "Marked 2"
  endif
'''

[[plugins]]
repo = 'zaiste/tmux.vim'
on_ft = 'tmux'

# [[plugins]]
# repo = 'Valloric/MatchTagAlways'
# on_ft = ['html', 'xhtml', 'xml', 'jinja', 'php']
# hook_add = '''
#   let g:mta_filetypes = {
#         \ 'html' : 1,
#         \ 'xhtml' : 1,
#         \ 'xml' : 1,
#         \ 'jinja' : 1,
#         \ 'php' : 1,
#         \}
# autocmd VimEnter,WinEnter,BufRead * hi MatchParen ctermfg=248 ctermbg=23 guifg=black guibg=lightgreen
#   nnoremap <leader>% :MtaJumpToOtherTag<cr>
#   " let g:mta_use_matchparen_group = 0
#   " let g:mta_set_default_matchtag_color = 0
#   " autocmd VimEnter,WinEnter,BufRead * highlight MatchTag ctermfg=248 ctermbg=23 guifg=black guibg=lightgreen
# '''
